version: '3.5'

services:
  api01: &api
    image: diegofsousa/rinha
    hostname: api01
    ports:
      - "3001:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"
  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
  db:
    container_name: db
    hostname: db
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rinha
      TZ: GMT-3
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/1.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

volumes:
  db-data:

networks:
  default:
    driver: bridge
    name: rinha-network